before_script:
  - git submodule update --init --recursive
  - echo "Build Bitcoin Core"
  - pushd contrib/libnunchuk/contrib/bitcoin
  - ./autogen.sh
  - ./configure --without-gui --disable-zmq --with-miniupnpc=no --with-incompatible-bdb --disable-bench --disable-tests
  - make -j8
  - popd
  #- mkdir -p contrib/libnunchuk/contrib/sqlcipher/.libs
  #- cp /usr/local/lib/libsqlcipher.a contrib/libnunchuk/contrib/sqlcipher/.libs/libsqlcipher.a

build_mac:
  interruptible: true
  stage: build
  script:
    - rm -rf build
    - mkdir build && cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl -DCMAKE_PREFIX_PATH=/usr/local/opt/qt5/lib/cmake -DUR__DISABLE_TESTS=ON
    # - cmake --build . --config Release -j8
    # - cp ../../../../../../manually/macdeploynunchuk/hwi nunchuck-client-qt.app/Contents/MacOS
    - export PATH="/usr/local/opt/qt@5/bin:$PATH"
    # - pwd
    # - ls -la
    # - macdeployqt nunchuck-client-qt.app
    # - macdeployqt nunchuck-client-qt.app -qmldir=..
    - for i in 1 2 3 4 5; do rm -rf nunchuck-client-qt.app nunchuck-client-qt.dmg;cmake --build . --config Release -j8;cp ../../../../../../manually/macdeploynunchuk/hwi nunchuck-client-qt.app/Contents/MacOS;macdeployqt nunchuck-client-qt.app -qmldir=.. -dmg && break || sleep 15; done
  tags:
    - build, macos, ci
  only:
    - ci
  artifacts:
   paths:
     - build/nunchuck-client-qt.dmg
